app/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.urls import re_path

from django.views.generic.base import TemplateView
from haystack.generic_views import SearchView

from app.views import HomeView, RedactorUploadView,CleanCacheView, RequestsComplaintsView
from app.forms import FileForm, ImageForm
from app.sitemaps import sitemaps
from shop.views import UpdateShopProducts
from shop.views import CitySearch
from common.views import ContactView
from common.views import OfficeListView
from common.views import ContactFormView
from cms.views import SatelliteMonitoringContactView
from cms.views import ReportSatelliteXls
from product.views import XmlUpdateView


urlpatterns = [
    # Home
    path('', HomeView.as_view(), name='home'),

    path(
        'robots.txt',
        TemplateView.as_view(template_name='robots.txt'),
    ),

    # Admin URLs
    path(
        'admin/clean_cache/',
        CleanCacheView.as_view(),
        name='clean_cache',
    ),
    path(
        'admin/cat_xml_sync/',
        XmlUpdateView.as_view(),
        name='cat_xml_sync',
    ),
    path(
        'admin/update_shop_products/',
        UpdateShopProducts.as_view(),
        name='update_shop_products',
    ),
    path(
        'admin/satellite_interest_report/',
        ReportSatelliteXls.as_view(),
        name='download_satellite_report',
    ),
    path('admin/', admin.site.urls),
    re_path(
        r'^admin/redactor/upload/image/(?P<upload_to>.*)$',
        RedactorUploadView.as_view(form_class=ImageForm),
        name='redactor_upload_image'
    ),
    re_path(
        r'^admin/redactor/upload/file/(?P<upload_to>.*)$',
        RedactorUploadView.as_view(form_class=FileForm),
        name='redactor_upload_file'
    ),

    path(
        'buscar/',
        SearchView.as_view(),
        name='search',
    ),

    path(
        'solicitudes-y-denuncias/',
        RequestsComplaintsView.as_view(),
        name='requests_complaints'
    ),

    # Monitoreo Satelital
    path(
        'monitoreo-satelital/',
        SatelliteMonitoringContactView.as_view(),
        name='satellital_tracking',
    ),

    # Sitemap
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='sitemap',
    ),

    # Contact
    path('contacto/', ContactView.as_view(), name='contact'),

    # Offices
    path('sedes/', OfficeListView.as_view(), name='office_list'),

    # shop
    path(
        'tienda/',
        include('shop.urls', namespace='shop')
    ),

    # CMS
    path(
        'maquinaria/',
        include('cms.urls', namespace='cms')
    ),

    # Products
    path(
        'equipos/',
        include('product.urls', namespace='equipment')
    ),

    # Usuarios
    path(
        'cuentas/',
        include('userprofile.urls', namespace='userprofile')
    ),

    # API City-Serch
    re_path(
        r'^city-search/(?P<query>.*)/$',
        CitySearch.as_view(), name='city-search'
    ),

    path(
        'contact_form_view/',
        ContactFormView.as_view(),
        name='contact_form',
    ),

    # API
    path(
        'api/',
        include('localapi.urls', namespace='api')
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

common/models.py
from django.db import models
from django.core.validators import RegexValidator


class SliderHome(models.Model):
    image_desktop = models.ImageField(
        max_length=256,
        upload_to='common/sliderhome/',
        verbose_name='imagen escritorio',
        help_text='2320x680 px PNG, JPG max 300 Kb',
    )

    image_mobile = models.ImageField(
        max_length=256,
        upload_to='common/sliderhome/',
        verbose_name='imagen mobile',
        help_text='1454x920 px PNG, JPG max 300 Kb',
    )

    image_tablet = models.ImageField(
        max_length=256,
        upload_to='common/sliderhome/',
        verbose_name='imagen tablet',
        help_text='1904x680 px PNG, JPG max 300 Kb',
    )

    url = models.CharField(
        max_length=256,
        verbose_name='enlace',
    )

    url_text = models.CharField(
        max_length=50,
        verbose_name='texto del enlace',
    )

    is_external = models.BooleanField(
        default=False,
        verbose_name='enlace externo',
    )

    position = models.PositiveIntegerField(
        verbose_name='posición',
        unique=True,
    )

    is_active = models.BooleanField(
        default=True,
        verbose_name='está activo?',
    )

    class Meta:
        verbose_name = 'slider del home'
        verbose_name_plural = 'sliders del home'
        ordering = ('position',)


class Alliance(models.Model):
    """ Related allied that appear in home.
    """
    title = models.CharField(
        max_length=100,
        verbose_name='título',
    )

    image = models.ImageField(
        max_length=256,
        upload_to='common/alliance/',
        verbose_name='imagen',
        help_text='La imagen debe tener el fondo blanco y 30 px de alto',
    )

    url = models.URLField(
        verbose_name='enlace',
    )

    position = models.PositiveIntegerField(
        verbose_name='posición',
        unique=True,
    )

    is_active = models.BooleanField(
        verbose_name='está activo',
        default=True,
    )

    def __str__(self):
        return '{0}'.format(self.title)

    class Meta:
        verbose_name = 'aliado'
        verbose_name_plural = 'aliados'
        ordering = ('position',)


class City(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name='título',
    )

    def __str__(self):
        return '{0}'.format(self.title)

    class Meta:
        verbose_name = 'ciudad'
        verbose_name_plural = 'ciudades'
        ordering = ('title',)


class Office(models.Model):
    CATEGORY_RENT = 1
    CATEGORY_FINANCE = 2
    CATEGORY_GECOLSA = 3
    CATEGORY_RELIANZ = 4
    CATEGORY_CHOICES = (
        (CATEGORY_RENT, 'Renta'),
        (CATEGORY_FINANCE, 'Financiación'),
        (CATEGORY_GECOLSA, 'Gecolsa'),
        (CATEGORY_RELIANZ, 'Relianz'),
    )

    title = models.CharField(
        max_length=100,
        verbose_name='título',
    )

    category = models.PositiveSmallIntegerField(
        verbose_name='categoría',
        choices=CATEGORY_CHOICES,
    )

    city = models.ForeignKey(
        'common.City',
        on_delete=models.CASCADE,
        verbose_name='ciudad',
        related_name='offices'
    )

    latlon = models.CharField(
        max_length=100,
        verbose_name='posición',
        validators=[RegexValidator(
            regex=r'^[-+]?[0-9]*\.?[0-9]+, [-+]?[0-9]*\.?[0-9]+$'
        )],
        help_text='Bogotá es: -74.18132, 4.31454'
    )

    phone = models.CharField(
        max_length=100,
        verbose_name='teléfono',
    )

    address = models.CharField(
        max_length=100,
        verbose_name='dirección',
    )

    schedule = models.TextField(
        verbose_name='horario',
    )

    is_active = models.BooleanField(
        verbose_name='está activo',
        default=True,
    )

    def get_lat(self):
        return self.latlon.split(',')[-1]

    def get_lon(self):
        return self.latlon.split(',')[0]

    def __str__(self):
        return '{0}'.format(self.title)

    class Meta:
        verbose_name = 'oficina'
        verbose_name_plural = 'oficinas'
        ordering = ('title',)


class FixedBlock(models.Model):
    """ Blocks used to show content on templates.
    """
    image = models.ImageField(
        max_length=256,
        upload_to='common/fixedblock/',
        verbose_name='imagen',
        help_text='El tamaño de la imagen debe ser de 1400 x 600 pixeles',
    )

    title = models.CharField(
        max_length=100,
        verbose_name='título',
    )

    slug = models.SlugField(
        unique=True,
    )

    summary = models.TextField(
        verbose_name='resumen',
    )

    def __str__(self):
        return '{0}'.format(self.title)

    class Meta:
        verbose_name = 'bloque fijo'
        verbose_name_plural = 'bloques fijos'
        ordering = ('title',)


class ImageLink(models.Model):
    """ Images with a related link used in categories.
    """
    SECTION_CHOICES = (
        ('communication', 'Comunicación'),
        ('contact', 'Contacto'),
        ('home', 'Home'),
        ('merchandise', 'Merchandise'),
        ('new-equipment', 'Nuevos'),
        ('office-list', 'Sedes'),
        ('subscribe', 'Suscripción'),
        ('used-equipment', 'Usados'),
    )

    image = models.ImageField(
        max_length=256,
        upload_to='common/imagelink/',
        verbose_name='imagen',
    )

    title = models.CharField(
        max_length=100,
        verbose_name='título',
    )

    section = models.CharField(
        max_length=100,
        choices=SECTION_CHOICES,
        verbose_name='section',
    )

    url = models.CharField(
        max_length=256,
        verbose_name='enlace',
    )

    is_external = models.BooleanField(
        default=False,
        verbose_name='enlace externo',
    )

    position = models.PositiveIntegerField(
        verbose_name='posición',
    )

    def __str__(self):
        return '{0}'.format(self.title)

    class Meta:
        verbose_name = 'imagen de enlace'
        verbose_name_plural = 'imágenes de enlace'
        ordering = ('position',)


class CompanyType(models.Model):
    title = models.CharField(
        max_length=100,
        verbose_name='título',
    )

    def __str__(self):
        return '{0}'.format(self.title)

    class Meta:
        verbose_name = 'tipo de industria'
        verbose_name_plural = 'tipos de industria'
        ordering = ('title',)


class Contact(models.Model):
    """ Stores contact form info.
    """
    CATEGORY_CONTACT_MAIN = 1
    CATEGORY_CONTACT_CLAIMS = 2
    CATEGORY_CONTACT_SALES = 3
    CATEGORY_CONTACT_OTHERS = 4
    CATEGORY_CONTACT_CHOICES = (
        (CATEGORY_CONTACT_MAIN, 'Contacto'),
        (CATEGORY_CONTACT_CLAIMS, 'Quejas y reclamos'),
        (CATEGORY_CONTACT_SALES, 'Asesoría comercial'),
        (CATEGORY_CONTACT_OTHERS, 'Otros asuntos'),
    )

    CATEGORY_BY_EMAIL = 10
    CATEGORY_BY_PHONE = 20
    CONTACT_BY_CHOICES = (
        (CATEGORY_BY_EMAIL, 'Email'),
        (CATEGORY_BY_PHONE, 'Teléfono'),
    )

    name = models.CharField(
        max_length=255,
        verbose_name='nombre',
    )

    mobile_number = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='celular',
    )

    email = models.EmailField(
        max_length=255,
        verbose_name='e-mail',
    )

    recipients = models.CharField(
        max_length=300,
        blank=True,
        verbose_name='categorias y correos',
    )

    comment = models.TextField(
        verbose_name='comentario',
    )

    contact_by = models.CharField(
        max_length=300,
        blank=True,
        verbose_name='tipo de contacto',
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='creado en',
    )

    full_path = models.CharField(
        max_length=255,
        verbose_name='URL de origen',
        blank=True,
    )

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        verbose_name = 'mensaje de contacto'
        verbose_name_plural = 'mensajes de contacto'
        ordering = ('-id',)


class WsLog(models.Model):
    """ Logging of webservices and results
    """

    endpoint = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='url',
    )

    status_code = models.PositiveSmallIntegerField(
        verbose_name='código resultado'
    )

    request_data = models.TextField(
        verbose_name='envío',
        blank=True,
    )

    answer_data = models.TextField(
        verbose_name='respuesta',
        blank=True,
    )

    ellapsed_time = models.DecimalField(
        max_digits=8,
        decimal_places=6,
        null=True,
        blank=True,
        verbose_name='tiempo de consulta'
    )

    category = models.CharField(
        max_length=255,
        blank=True,
        verbose_name='categoría',
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='creado en',
    )

    def __str__(self):
        return '{0}'.format(self.category)

    class Meta:
        verbose_name = 'log de webservice'
        verbose_name_plural = 'logs de webservices'
        ordering = ('-created_at',)

common/views.py
from django.conf import settings
from django.http import Http404
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic import TemplateView

import re

from app.utils import send_email
from common.forms import ContactForm
from common.forms import OfficeForm
from common.models import Office


class ContactView(TemplateView):
    template_name = 'common/contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        office_form = OfficeForm()
        office_form.fields['city'].label = ''
        context['office_form'] = office_form
        context['form'] = ContactForm

        return context


class ContactFormView(FormView):
    form_class = ContactForm

    def get(self, *args, **kwargs):
        raise Http404

    def form_valid(self, form):
        pattern = re.compile(r'(?!&)utm_[^=]*=[^&]*(?=&|$)')
        obj = form.save()
        obj.recipients = settings.DEFAULT_TO_EMAIL[0]
        obj.save()
        utm_list = re.findall(pattern, obj.full_path.rstrip())

        utm_dict = {}
        if utm_list:
            utm_dict = {
                utm.split('=')[0]: utm.split('=')[1] for utm in utm_list
            }

        send_email(
            '[GECOLSA] Contacto desde el portal web',
            [form.instance.email],
            'common/contact_email_user.html',
            {'contact': form.instance},
        )

        send_email(
            '[GECOLSA] Contacto desde el portal web',
            settings.DEFAULT_TO_EMAIL,
            'common/contact_email.html',
            {'contact': form.instance, 'utm_dict': utm_dict},
        )

        return JsonResponse({
            'ok': True,
            'message': 'Gracias por su interés, pronto le contactaremos.'
        })

    def form_invalid(self, form):
        return JsonResponse({
            'ok': False,
            'message': form.errors
        })


class OfficeListView(ListView):
    model = Office
    context_object_name = 'offices'
    search_city = None

    def dispatch(self, request, *args, **kwargs):
        """If is filtering by city check if the city is valid
        otherwise it will redirect the user to the office_list
        page.
        """
        if 'city' in request.GET and request.GET['city']:
            try:
                city_id = int(request.GET['city'])
            except ValueError:
                # Bad parameter
                return redirect('office_list')

            queryset = self.get_queryset().filter(city_id=city_id)
            if queryset:
                self.search_city = queryset.first().city
            else:
                # There are no offices matching the filter
                return redirect('office_list')

        return super(OfficeListView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(OfficeListView, self).get_queryset()

        queryset = queryset.filter(is_active=True)
        if self.search_city:
            queryset = queryset.filter(city=self.search_city)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(OfficeListView, self).get_context_data(**kwargs)

        if self.search_city:
            office_form = OfficeForm(initial={'city': self.search_city})
        else:
            office_form = OfficeForm()

        context['office_form'] = office_form
        context['search_city'] = self.search_city

        return context

common/templates/common/_contact_form.html
{% load static %}
    <form method="POST" action="{% url 'contact_form' %}" class="js-contact-form contact-form">
        <h6 class="form-title">CONTÁCTENOS</h6>
        {% csrf_token %}
        {{ form }}
        <a href="https://gecolsa.com/maquinaria/legal-general/">Acepto términos y condiciones</a>
        <button type="submit" class="yellow-link-box send_yellow_button">
            <span>Enviar</span>
            <svg class="icon">
                <use xlink:href="{% static 'svg/icons.svg' %}#arrow-btn"></use>
            </svg>
        </button>
    </form>

common/templates/common/contact.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags block_tags static %}

{% block title %}Contacto |{% endblock %}

{% block header %}
{% with 'contact'|get_fixed_block as block %}
    <div class="text-heading" style="background-image: url({{ block.image.url }});">
        <div class="container">
            <h1>{{ block.title }}</h1>
            <div class="summary">{{ block.summary }}</div>
        </div>
    </div>
{% endwith %}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumb-container">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li class="active">Contacto</li>
        </ol>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="contact-form">
    <div class="toll-free-banner text-center">
        <h5><span class="gp-img-md-yellow-phone icon"></span> LÍNEA GRATUITA NACIONAL <span>{{ config.PHONE_CONTACT }}</span></h5>
    </div>
    <div class="flex-link-list">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 {% if config.CHAT_URL %}col-sm-4{% else %}col-sm-6{% endif %} email">
                    <a href="mailto:{{ email_contact }}" class="fluid-content">
                        <h6>CORREO ELECTRÓNICO</h6>
                        <span>{{ email_contact }}</span>
                    </a>
                </div>
                {% if config.CHAT_URL %}
                <div class="col-xs-12 col-sm-4 chat">
                    <a class="js-chat-popup fluid-content" href="{{ config.CHAT_URL }}">
                        <h6>CHAT</h6>
                        <span>Comuníquese con nosotros</span>
                    </a>
                </div>
                {% endif %}
                <div class="col-xs-12 {% if config.CHAT_URL %}col-sm-4{% else %}col-sm-6{% endif %} offices">
                    <a href="{% url 'office_list' %}" class="fluid-content">
                        <h6>NUESTRAS SEDES</h6>
                        <span>Encuentre la sede más cercana</span>
                    </a>
                </div>
            </div>
        </div>
    </div>

    {% if object %}
        {% include 'search/_rendered.html' with object=object %}
    {% endif %}

    <div class="container">
        <p>Completa el siguiente formulario, selecciona el tema que describa con mayor exactitud tus necesidades, haz clic en el botón "Enviar" y en breve uno de nuestros especialistas y/o área de servicio al cliente se pondrá en contacto contigo, para brindarte la información solicitada.</p>

        <p class="form-info">Todos los campos marcados con asterisco (*) son obligatorios.</p>

        {% include 'common/_contact_form.html' %}

    </div>
    {% comment %}
    {% get_link_list 'contact' %}
    {% endcomment %}
</div>
{% endblock %}

common/templates/common/contact_email.html
{% extends "layout/base_email.html" %}
{% block content %}
<p>Hemos recibido mensaje de contacto de <b>{{ contact.name|capfirst }}</b>, <a href="mailto:{{ contact.email }}">{{ contact.email }}</a>.</p>

<ul>
    <li><b>Celular</b>: {{ contact.mobile_number|default:"N/A" }}</li>
    <li><b>Comentario</b>: {{ contact.comment }} </li>
    <li><b>Lugar de contacto</b>: {{ contact.contact_by }} </li>
    <li><b>Url</b>: <a href="{{ contact.full_path }}">Ver más</a></li>
    {% if link %}<li><b>Interesado en</b>: <a href="{{ link }}">{{ link }}</a></li>{% endif %}
{% if utm_dict %}
{% for key, value in utm_dict.items %}
    <li><b>{{ key }}</b>: {{ value }} </li>
{% endfor %}
{% endif %}
</ul>

{% endblock %}

common/templates/common/contact_email_user.html
{% extends "layout/base_email.html" %}
{% block content %}
<p>{{ contact.name|capfirst }}, hemos recibido su mensaje de contacto.</p>

<ul>
    <li><b>Celular</b>: {{ contact.mobile_number|default:"N/A" }}</li>
    <li><b>Email</b>: {{ contact.email }} </li>
    <li><b>Comentario</b>: {{ contact.comment }} </li>
    <li><b>Lugar de contacto</b>: {{ contact.contact_by }} </li>
    <li><b>Url</b>: <a href="{{ contact.full_path }}">Ver más</a></li>
</ul>

<p>Gracias por su interés, estaremos contactándole.</p>

{% endblock %}
lorem50

common/templates/common/image_link_list.html
{% if link_list %}
<div class="image-link-list">
    <div class="container-fluid">
        <div class="row">
        {% for link in link_list %}
            <div class="col-sm-12 col-md-4" style="background-image:url('{{ link.image.url }}')">
                <a href="{{ link.url }}" {% if link.is_external %}target="_blank"{% endif %}>{{ link.title }}</a>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endif %}

common/templates/common/office_list.html
{% extends 'layout/base.html' %}
{% load static crispy_forms_tags block_tags %}

{% block title %}Sedes |{% endblock %}

{% block header %}
{% with 'offices'|get_fixed_block as block %}
    <div class="text-heading" style="background-image: url({{ block.image.url }});">
        <div class="container">
            <h1>{{ block.title }}</h1>
            <div class="summary">{{ block.summary }}</div>
        </div>
    </div>
{% endwith %}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumb-container">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li class="active">Sedes</li>
        </ol>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="office-list">
    <div class="container">

        <div class="city-selector text-center">
            {% crispy office_form %}
        </div>

        <div class="office-list-boxes clearfix">
        {% for office in offices %}
            <div class="office col-md-4">
                <p>
                {% if office.category == office.CATEGORY_RENT %}
                    <span class="gp-img-label-gecolsa-rental"></span>
                    <span class="rental">{{ office.get_category_display }}</span>

                {% elif office.category == office.CATEGORY_FINANCE %}
                    <span class="gp-img-label-gecolsa-rental"></span>
                    <span class="rental">{{ office.get_category_display }}</span>

                {% elif office.category == office.CATEGORY_GECOLSA %}
                    <span class="gp-img-label-gecolsa-cat"></span>
                    <span class="gecolsa">{{ office.get_category_display }}</span>
                {% endif %}

                </p>
                <h6>{{ office.title }}</h6>
                <p>
                    <span>{{ office.address }}</span>
                    <span><strong>Teléfono:</strong> {{ office.phone }}</span>
                </p>
                <p>
                    <span><strong>Horario de atención:</strong></span>
                    <span>{{ office.schedule }}</span>
                </p>
            </div>
        {% endfor %}
        </div>

        <div class="map-wrapper">
            <div id="map_offices" style="width: 100%; height: 545px"></div>
        </div>

    </div>
    {% get_link_list 'office-list' %}

</div>
{% endblock %}

{% block extra_head %}
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?sensor=true"></script>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        var MARKERS = [
        {% for office in offices %}
            [
                {{ office.get_lat }},
                {{ office.get_lon }},
                {% if office.category == office.CATEGORY_RENT %}
                    "{% static 'img/pin_renta.png' %}"
                {% else %}
                    "{% static 'img/pin_gecolsa.png' %}"
                {% endif %},
            ]{% if not forloop.last %},{% endif %}
        {% endfor %}
        ];

        function initialize_map() {
            var mapOptions = {
                maxZoom: 17,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                scrollwheel: false,
                zoomControl: true
            };

            var map = new google.maps.Map(document.getElementById('map_offices'), mapOptions);

            google.maps.event.addListenerOnce(map, 'zoom_changed', function() {
                var oldZoom = map.getZoom();
                map.setZoom(oldZoom - 1);
            });

            var bounds = new google.maps.LatLngBounds();
            for (i = 0; i < MARKERS.length; i++) {
                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(MARKERS[i][0], MARKERS[i][1]),
                    map: map,
                    icon: MARKERS[i][2]
                });
                bounds.extend(marker.getPosition());
            }

            map.fitBounds(bounds);
        }

        $(function() {
            initialize_map();
            google.maps.event.addDomListener(window, 'resize', initialize_map);
            google.maps.event.addDomListener(window, 'load', initialize_map);
        });

        $('#id_city').on('change', function() {
            $(this).closest('form').submit();
        });
    </script>
{% endblock %}