app/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.urls import re_path

from django.views.generic.base import TemplateView
from haystack.generic_views import SearchView

from app.views import HomeView, RedactorUploadView,CleanCacheView, RequestsComplaintsView
from app.forms import FileForm, ImageForm
from app.sitemaps import sitemaps
from shop.views import UpdateShopProducts
from shop.views import CitySearch
from common.views import ContactView
from common.views import OfficeListView
from common.views import ContactFormView
from cms.views import SatelliteMonitoringContactView
from cms.views import ReportSatelliteXls
from product.views import XmlUpdateView


urlpatterns = [
    # Home
    path('', HomeView.as_view(), name='home'),

    path(
        'robots.txt',
        TemplateView.as_view(template_name='robots.txt'),
    ),

    # Admin URLs
    path(
        'admin/clean_cache/',
        CleanCacheView.as_view(),
        name='clean_cache',
    ),
    path(
        'admin/cat_xml_sync/',
        XmlUpdateView.as_view(),
        name='cat_xml_sync',
    ),
    path(
        'admin/update_shop_products/',
        UpdateShopProducts.as_view(),
        name='update_shop_products',
    ),
    path(
        'admin/satellite_interest_report/',
        ReportSatelliteXls.as_view(),
        name='download_satellite_report',
    ),
    path('admin/', admin.site.urls),
    re_path(
        r'^admin/redactor/upload/image/(?P<upload_to>.*)$',
        RedactorUploadView.as_view(form_class=ImageForm),
        name='redactor_upload_image'
    ),
    re_path(
        r'^admin/redactor/upload/file/(?P<upload_to>.*)$',
        RedactorUploadView.as_view(form_class=FileForm),
        name='redactor_upload_file'
    ),

    path(
        'buscar/',
        SearchView.as_view(),
        name='search',
    ),

    path(
        'solicitudes-y-denuncias/',
        RequestsComplaintsView.as_view(),
        name='requests_complaints'
    ),

    # Monitoreo Satelital
    path(
        'monitoreo-satelital/',
        SatelliteMonitoringContactView.as_view(),
        name='satellital_tracking',
    ),

    # Sitemap
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='sitemap',
    ),

    # Contact
    path('contacto/', ContactView.as_view(), name='contact'),

    # Offices
    path('sedes/', OfficeListView.as_view(), name='office_list'),

    # shop
    path(
        'tienda/',
        include('shop.urls', namespace='shop')
    ),

    # CMS
    path(
        'maquinaria/',
        include('cms.urls', namespace='cms')
    ),

    # Products
    path(
        'equipos/',
        include('product.urls', namespace='equipment')
    ),

    # Usuarios
    path(
        'cuentas/',
        include('userprofile.urls', namespace='userprofile')
    ),

    # API City-Serch
    re_path(
        r'^city-search/(?P<query>.*)/$',
        CitySearch.as_view(), name='city-search'
    ),

    path(
        'contact_form_view/',
        ContactFormView.as_view(),
        name='contact_form',
    ),

    # API
    path(
        'api/',
        include('localapi.urls', namespace='api')
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

cms/urls.py
from django.views.generic import TemplateView
from django.urls import path

from cms.views import CommunicationListView
from cms.views import CommunicationDetailView
from cms.views import PageDetailView

app_name = 'cms'
urlpatterns = [
    path(
        'comunicacion/',
        CommunicationListView.as_view(),
        name='communication_list',
    ),

    path(
        'comunicacion/categoria/<slug:slug>/',
        CommunicationListView.as_view(),
        name='communication_by_category_list',
    ),

    path(
        'comunicacion/<slug:slug>/',
        CommunicationDetailView.as_view(),
        name='communication_detail',
    ),

    path(
        'reparacion/nivel-de-reparacion/',
        TemplateView.as_view(template_name="cms/_repair_level.html"),
        name='repair'
    ),

    path(
        '<slug:slug>/',
        PageDetailView.as_view(),
        name='page_detail',
    ),
]

cms/views.py
from django.contrib import messages
from django.contrib.sites.models import Site
from django.urls import reverse
from django.urls import reverse_lazy
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.utils.html import strip_tags
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import View


from braces.views import SuperuserRequiredMixin
from constance import config

from app.utils import send_email
from cms.forms import SatelliteMonitoringContactForm
from cms.models import Communication
from cms.models import CommunicationCategory
from cms.models import Page
from cms.models import SatelliteMonitoringContact
from cms.tasks import task_send_satellite_report
from common.forms import ContactForm


class CommunicationListView(ListView):
    model = Communication
    context_object_name = 'communications'
    communication_category = None

    def dispatch(self, request, *args, **kwargs):
        if 'slug' in self.kwargs and self.kwargs['slug']:
            try:
                self.communication_category = \
                    CommunicationCategory.objects.get(slug=self.kwargs['slug'])
            except CommunicationCategory.DoesNotExist:
                self.communication_category = None
        return super(
            CommunicationListView,
            self,
        ).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(CommunicationListView, self).get_queryset()
        queryset = queryset.filter(is_active=True)
        if self.communication_category:
            queryset = queryset.filter(category=self.communication_category)
        return queryset.select_related('category')

    def get_context_data(self, **kwargs):
        context = super(CommunicationListView, self).get_context_data(**kwargs)
        context['communication_categories'] = \
            CommunicationCategory.objects.filter(
                communication__is_active=True,
        ).distinct()
        context['current_communication_category'] = self.communication_category
        return context


class CommunicationDetailView(DetailView):
    model = Communication
    context_object_name = 'communication'

    def get(self, *args, **kwargs):
        if not self.get_object().is_active:
            raise Http404
        return super(
            CommunicationDetailView,
            self,
        ).get(*args, **kwargs)


class PageDetailView(DetailView):
    model = Page
    context_object_name = 'page'

    def get(self, *args, **kwargs):
        if not self.get_object().is_active:
            raise Http404
        if (
            not self.get_object().children.exists() and
            not strip_tags(self.get_object().content)
        ):
            if self.get_object().parent:
                return redirect(reverse(
                    'cms:page_detail',
                    args=[self.get_object().parent.slug]
                ))
            else:
                raise Http404

        return super(
            PageDetailView,
            self,
        ).get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ContactForm()
        return context


class SatelliteMonitoringContactView(CreateView):
    template_name = 'cms/satellite_monitoring.html'
    model = SatelliteMonitoringContact
    form_class = SatelliteMonitoringContactForm
    success_url = reverse_lazy('home')
    bcc_list = None

    def dispatch(self, request, *args, **kwargs):
        self.bcc_list = [config.EMAIL_SATELITAL]
        return super(
            SatelliteMonitoringContactView,
            self
        ).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        site = Site.objects.get_current().name
        send_email(
            '[{0}] Registro de monitoreo satelital'.format(site),
            [form.instance.email],
            'cms/satellite_monitoring_email.html',
            {'contact': form.instance},
            from_addr=config.EMAIL_SATELITAL,
            bcc_mails=self.bcc_list,
        )
        messages.info(
            self.request,
            'Gracias por su interés, pronto le contactaremos.',
        )

        return super(SatelliteMonitoringContactView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(SatelliteMonitoringContactView, self).get_context_data(
            **kwargs
        )
        context['email_contact'] = self.bcc_list[0]

        return context


class ReportSatelliteXls(SuperuserRequiredMixin, View):
    def get(self, *args, **kwargs):
        task_send_satellite_report.delay(
            [self.request.user.email],
        )
        messages.info(
            self.request,
            'Recibirá un correo con la información solicitada',
        )

        return HttpResponseRedirect(reverse('admin:index'))

cms/templates/cms/_accordion.html
{% if page.is_active %}
{% with page.get_parents as current_page_parents %}
<div class="list-group pages-list-group hidden-sm hidden-xs {% if page.show_children and page.children.exists %}show-children{% endif %}">
{% for second_level_page in second_level_pages %}
{% if second_level_page.is_active %}
    <a href="{{ second_level_page.get_absolute_url }}" class="list-group-item gp-accordion-second-level {% if second_level_page == page or second_level_page in current_page_parents %}active{% endif %}">{{ second_level_page }}</a>
    {% if second_level_page == page or second_level_page in current_page_parents %}
        {% for third_level_page in second_level_page.children.all %}
        {% if third_level_page.is_active and third_level_page.content|length > 20 %}
            <a href="{{ third_level_page.get_absolute_url }}" class="list-group-item gp-accordion-third-level {% if third_level_page == page or third_level_page in current_page_parents %}active{% endif %}">{{ third_level_page }}</a>
            {% if third_level_page == page or third_level_page in current_page_parents %}
                {% for forth_level_page in third_level_page.children.all %}
                    {% if forth_level_page.is_active and forth_level_page.content|length > 20 %}
                    <a href="{{ forth_level_page.get_absolute_url }}" class="list-group-item gp-accordion-forth-level {% if forth_level_page == page or forth_level_page in current_page_parents %}active{% endif %}">{{ forth_level_page }}</a>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endif %}
        {% endfor %}
    {% endif %}
{% endif %}
{% endfor %}
</div>
{% endwith %}
{% endif %}

cms/templates/cms/_children_with_content.html
{% load product_tags static %}
<!-- CHILDREN LIST LAYOUT -->

<div class="gp-page-item {% if forloop.counter|divisibleby:2 %}even{% endif %}">
    <div class="container">
        <div class="gird-2">
            <div class="col-grid-2 lazy-page-img">
        {% if page_child.list_image %}
            {% image_style page_child.list_image "page" as image_style %}
            {% if image_style %}
                <a href="{{ page_child.get_absolute_url }}"><img class="lazy" data-original="{{ page_child.list_image.url }}" alt="{{ page_child.title }}"></a>
            {% endif %}
        {% endif %}
            </div>
            <div class="col-grid-2">
                <h5><a href="{{ page_child.get_absolute_url }}">{{ page_child }}</a></h5>
                <div class="gp-page-text">{{ page_child.summary|safe }}</div>
                <a class="yellow-link-box" href="{{ page_child.get_absolute_url }}">
                    <span>Ver más</span>
                    <svg class="icon">
                        <use xlink:href="{% static 'svg/icons.svg' %}#arrow-btn"></use>
                    </svg>
                </a>
            </div>
        </div>
    </div>
</div>

cms/templates/cms/_children_without_content.html
{% load product_tags static %}
<!-- CHILDREN LIST LAYOUT -->
<div class="gp-page-item {% if forloop.counter|divisibleby:2 %}even{% endif %}">
    <div class="container">
        <div class="gird-2">
            <div class="col-grid-2">
        {% if page_child.list_image %}
            {% image_style page_child.list_image "page" as image_style %}
            {% if image_style %}
                <img class="lazy" data-original="{{ page_child.list_image.url }}" alt="{{ page_child.title }}">
            {% endif %}
        {% endif %}
            </div>
            <div class="col-grid-2">
                <h5>{{ page_child }}</h5>
                <div class="gp-page-text">{{ page_child.summary|safe }}</div>
                {% for file in page_child.related_files.all %}
                <div class="related-link">
                    <a class="yellow-link-box" target="_blank" href="{{ file.image.url }}">
                        <span>{{ file.title }}</span>
                        <svg class="icon">
                            <use xlink:href="{% static 'svg/icons.svg' %}#download-btn"></use>
                        </svg>
                    </a>
                </div>
                {% endfor %}

                {% for related_link in page_child.related_links.all %}
                <div class="related-link">
                    <a class="yellow-link-box" href="{{ related_link.url }}">
                        <span>{{ related_link.title }}</span>
                        <svg class="icon">
                            <use xlink:href="{% static 'svg/icons.svg' %}#arrow-btn"></use>
                        </svg>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

cms/templates/cms/_links_and_files.html
{% load static %}
{% if page.related_files.all or page.related_links.all %}

    <div class="related-links">
        <div class="container">
        {% for related_file in page.related_files.all %}
            <div class="related-link">
                <a class="yellow-link-box" target="_blank" href="{{ related_file.image.url }}">
                    <span>{{ related_file.title }}</span>
                    <svg class="icon">
                        <use xlink:href="{% static 'svg/icons.svg' %}#download-btn"></use>
                    </svg>
                </a>
            </div>
        {% endfor %}

        {% for related_link in page.related_links.all %}
            <div class="related-link">
                <a class="yellow-link-box" href="{{ related_link.url }}">
                    <span>{{ related_link.title }}</span>
                    <svg class="icon">
                        <use xlink:href="{% static 'svg/icons.svg' %}#arrow-btn"></use>
                    </svg>
                </a>
            </div>
        {% endfor %}
        </div>
    </div>
{% endif %}

cms/templates/cms/_page_children.html
<div class="gp-page-list">
{% for page_child in page.children.all %}
    {% if page_child.content|length > 20 or page_child.children.exists %}
        {% include "cms/_children_with_content.html" %}
    {% else %}
        {% include "cms/_children_without_content.html" %}
    {% endif %}
{% endfor %}
</div>

cms/templates/cms/_page_content_detail.html
{% load static thumbnail %}
<div class="gp-page-detail">
    <div class="navegation-menu">
        <a href="#" class="link-icon back-btn js-back-btn">
            <div class="circle">
                <svg class="icon">
                    <use xlink:href="{% static 'svg/icons.svg' %}#arrow"></use>
                </svg>
            </div>
            <div class="text">Atras</div>
        </a>
    </div>
    <div class="gp-description {% if page.show_content and page.show_children %} with-list{% endif %}">
        <div class="container gp-page-text">{{ page.content|safe }}</div>

        {% include 'cms/_links_and_files.html' %}

            {% if page.gallery.exists %}
            <div class="carousel-container">
                <div class="js-carousel">
                {% for gallery_slide in page.gallery.all %}
                    <div class="slide">
                        {% thumbnail gallery_slide.image "800x380" crop="center" as im %}
                            <img src="{{ im.url }}" alt="{{ gallery_slide.title }}">
                        {% endthumbnail %}
                    </div>
                {% endfor %}
                </div>
                <a class="image-zoom js-zoom" href="#">
                    <svg class="icon">
                        <use xlink:href="{% static 'svg/icons.svg' %}#magnifying-glass"></use>
                    </svg>
                    <span>Ampliar foto</span>
                </a>
            </div>
            {% endif %}

        {% if page.has_contact %}
        <div class="related-link">
            <a class="yellow-link-box" href="{% url 'contact' %}?page={{ page.id }}">
                <span>MAYOR INFORMACIÓN</span>
                <svg class="icon">
                    <use xlink:href="{% static 'svg/icons.svg' %}#arrow-btn"></use>
                </svg>
            </a>
        </div>
        {% endif %}
    </div>
</div>

cms/templates/cms/communication_detail.html
{% extends "layout/base.html" %}
{% load static thumbnail block_tags %}

{% block title %}{{ communication.title }} - Comunicación |{% endblock %}

{% block meta_title %}{{ communication.meta_title }}{% endblock %}

{% block meta_description %}{{ communication.meta_description }}{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'node_modules/slick-carousel/slick/slick.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'node_modules/slick-carousel/slick/slick-theme.css' %}">
{% endblock %}

{% block header %}
<div class="text-heading communication-heading" style="background-image: url({{ communication.image.url }});">
    <div class="container">
        <div class="summary">
            {{ communication.category.title|safe }}
        </div>
        <h1>{{ communication.title }}</h1>
    </div>
</div>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumb-container">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'cms:communication_list' %}">Comunicación</a></li>
            <li><a href="{{ communication.category.get_absolute_url }}">{{ communication.category.title }}</a></li>
            <li class="active">{{ communication.title }}</li>
        </ol>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="communication-detail page-detail">
    <div class="container">
        <div class="comunication-container">
            <div class="navegation-menu">
                <a href="#" class="link-icon back-btn js-back-btn">
                    <div class="circle">
                        <svg class="icon">
                            <use xlink:href="{% static 'svg/icons.svg' %}#arrow"></use>
                        </svg>
                    </div>
                    <div class="text">Atras</div>
                </a>
            </div>

            {% if communication.category.slug == 'eventos' %}
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td>FECHA{% if communication.event_hour %} - HORA {% endif %}</td>
                            {% if communication.end_date %}
                                <td>FECHA FINAL</td>
                            {% endif %}
                                <td>CIUDAD</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ communication.event_date }} {% if communication.event_hour %}{{ communication.event_hour }}{% endif %}</td>
                            {% if communication.end_date %}
                                <td>{{ communication.end_date }}</td>
                            {% endif %}
                                <td>{{ communication.event_city }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            {% endif %}
            {% if communication.event_place %}
                <p><b>Lugar: </b>{{ communication.event_place }}</p>
            {% endif %}

            {{ communication.content|safe }}

        </div>

            {% if communication.gallery.exists %}
            <div class="carousel-container">
                <div class="js-carousel">
                {% for gallery_slide in communication.gallery.all %}
                    <div class="slide">
                    {% thumbnail gallery_slide.image "800x380" crop="center" as im %}
                        <img src="{{ im.url }}" alt="{{ gallery_slide.title }}">
                    {% endthumbnail %}
                    </div>
                {% endfor %}
                </div>
                <a class="image-zoom js-zoom" href="#">
                    <svg class="icon">
                        <use xlink:href="{% static 'svg/icons.svg' %}#magnifying-glass"></use>
                    </svg>
                    <span>Ampliar foto</span>
                </a>
            </div>
            {% endif %}

        <div class="comunication-container">
            {{ communication.extended_content|safe }}

            {% for file in communication.related_files.all %}
                <div class="related-link">
                    <a class="yellow-link-box" target="_blank" href="{{ file.image.url }}">
                        <span>{{ file.title }}</span>
                        <svg class="icon">
                            <use xlink:href="{% static 'svg/icons.svg' %}#download-btn"></use>
                        </svg>
                    </a>
                </div>
            {% endfor %}
            {% if communication.has_contact %}
                <div class="related-link">
                    <a class="yellow-link-box" href="{% url 'contact' %}?communication={{ communication.id }}">
                        <span>MAYOR INFORMACIÓN</span>
                        <svg class="icon">
                            <use xlink:href="{% static 'svg/icons.svg' %}#arrow-btn"></use>
                        </svg>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
    {% if communication.category.has_share_buttons %}
        <div class="container-shared">
            <div class="container">
                <h4>Comparte este artículo</h4>
                <div class="addthis_inline_share_toolbox"></div>
            </div>
        </div>
    {% endif %}

    {% if communication.category.has_comments %}
        <div class="container-comments">
            <div class="container">
                <h4>Comentarios</h4>
                <div class="disqus-thread" id="disqus_thread"></div>
            </div>
        </div>
    {% endif %}
</div>

<div class="hide">
{% if communication.gallery.exists %}
    {% for gallery_slide in communication.gallery.all %}
        <a class="full-size-image" data-lightbox="communication" href="{{ gallery_slide.image.url }}" data-title="{{ forloop.counter }}"></a>
    {% endfor %}
{% endif %}
</div>

{% if communication.has_footer %}
    {% get_link_list communication %}
{% endif %}
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-57bb30e62caa7058"></script>
{% endblock %}

{% block js %}
<script src="{% static 'node_modules/slick-carousel/slick/slick.min.js' %}"></script>
<script src="{% static 'js/communication.js' %}"></script>
<script>
(function() {
    var d = document, s = d.createElement('script');
    s.src = '//gecolsa.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);

    $('.related-link a.yellow-link-box').on('click', function() {
        ga('send', 'event', 'more_info', 'click');
    });
})();
</script>
{% endblock %}

cms/templates/cms/communication_list.html
{% extends "layout/base.html" %}
{% load product_tags block_tags static %}

{% block title %}Comunicación |{% endblock %}

{% block header %}
{% with 'communication'|get_fixed_block as block %}
    <div class="text-heading" style="background-image: url({{ block.image.url }});">
        <div class="container">
            <h1>{{ block.title }}</h1>
            <div class="summary">{{ block.summary }}</div>
        </div>
    </div>
{% endwith %}
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumb-container">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
        {% if current_communication_category %}
            <li><a href="{% url 'cms:communication_list' %}">Comunicación</a></li>
            <li class="active">{{ current_communication_category.title }}</li>
        {% else %}
            <li class="active">Comunicación</li>
        {% endif %}
        </ol>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="communication-list home">
    <div class="nav-container">
        <div class="container">
            <ul class="nav nav-pills">
                <li {% if not current_communication_category %}class="active"{% endif %}><a href="{% url 'cms:communication_list' %}">Todos</a></li>
            {% for communication_category in communication_categories %}
                <li {% ifequal communication_category current_communication_category %}class="active"{% endifequal %}>
                    <a href="{% url 'cms:communication_by_category_list' communication_category.slug %}">{{ communication_category.title }}</a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="comunicaction-list-item container js-masonry">
        {% for communication in communications %}
            <div class="item">
                <a href="{{ communication.get_absolute_url }}">
                {% image_style communication.list_image "communication" as image_style %}
                {% if image_style %}
                    <div class="cover-image lazy" data-original="{{ communication.list_image.url }}" style="background-image:url({% static 'img/background-gray.png' %}){% if forloop.counter != 2 %};background-position:0 50%{% endif %}; background-size: cover;"></div>
                {% endif %}
                    <div class="info-comunication">
                        <div class="category">{{ communication.category }}</div>
                        <h2>{{ communication.title }}</h2>
                        <p>{{ communication.content|striptags|safe|truncatechars:300 }}</p>
                        <a href="{{ communication.get_absolute_url }}" class="link-icon">
                            <div class="text">Ver más</div>
                            <div class="circle">
                                <svg class="icon">
                                    <use xlink:href="{% static 'svg/icons.svg' %}#arrow"></use>
                                </svg>
                            </div>
                        </a>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% if not current_communication_category %}
    {% get_link_list 'communication' %}
{% elif current_communication_category.has_footer %}
    {% get_link_list current_communication_category %}
{% endif %}
{% endblock %}

{% block js %}
<script src="{% static 'node_modules/masonry-layout/dist/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'node_modules/slick-carousel/slick/slick.min.js' %}"></script>
<script src="{% static 'node_modules/jquery_lazyload/jquery.lazyload.js' %}"></script>
<script src="{% static 'js/communication.js' %}"></script>

<script type="text/javascript">
$(function() {
    'use strict';
    $('.js-masonry').masonry({
      itemSelector: '.item',
    });
});
</script>

{% endblock %}

cms/templates/cms/page_detail.html
{% extends "layout/base.html" %}
{% load cms_tags static %}

{% block title %}{{ page.title }} |{% endblock %}

{% block meta_description %}{{ page.meta_description }}{% endblock %}

{% block meta_title %}{{ page.meta_title }}{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'node_modules/slick-carousel/slick/slick.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'node_modules/slick-carousel/slick/slick-theme.css' %}">
{% endblock %}

{% block header %}
<div class="text-heading" style="background-image: url({{ page.get_image.url }});">
    <div class="container">
    {% if page.embed_video_url %}
        <div class="videoGrid">
            <div class="col">
                <h1>{{ page.title }}</h1>
                <div class="summary">{{ page.summary|safe }}</div>
            </div>
            <div class="col">
                <div class="video-wrapper">
                    <iframe src="{{ page.embed_video_url }}" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    {% else %}
        <h1>{{ page.title }}</h1>
        <div class="summary image">{{ page.summary|safe }}</div>
    {% endif %}
    </div>
</div>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumb-container">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
        {% for parent in page.get_parents %}
            <li><a href="{{ parent.get_absolute_url }}">{{ parent.title }}</a></li>
        {% endfor %}
            <li class="active">{{ page.title }}</li>
        </ol>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="page-detail {% if page.has_children_accordion %}with-accordion{% endif %}">
{% if page.has_children_accordion and page.get_parents %}
    <div class="container">
        <div class="accordion-page-container">
            <div class="col-page-accordion">{% get_accordion page %}</div>
            <div class="col-page-accordion">
    {% if page.content|length < 20 and page.children.exists %}
        {% include "cms/_page_children.html" %}
    {% else %}
            <!-- PAGE DETAIL LAYOUT -->

            {% include "cms/_page_content_detail.html"  %}

            {% include 'common/_contact_form.html' %}

    {% endif %}
            </div>
        </div>
    </div>
{% else %}
    {% if not page.children.exists %}
    <div class="container">{% include "cms/_page_content_detail.html"  %}</div>
    {% else %}
        {% include "cms/_page_children.html" %}
    {% endif %}
{% endif %}
</div>

<div class="hide">
{% for gallery_slide in page.gallery.all %}
    <a class="full-size-image" data-lightbox="equipment" href="{{ gallery_slide.image.url }}" data-title="{{ forloop.counter }}"></a>
{% endfor %}
</div>
{% endblock %}

{% block js %}
<script src="{% static 'node_modules/slick-carousel/slick/slick.min.js' %}"></script>
<script src="{% static 'node_modules/jquery_lazyload/jquery.lazyload.js' %}"></script>
<script src="{% static 'js/page-basic.js' %}"></script>
{% endblock %}